### PR TITLE
Spacing adjustment

### PR DESCRIPTION
**Pull request by lyubomir-popov**
## Done

This is a work in progress branch that aims to:
- make text spacing slightly simplified
- make shallow strip match the standard bottom spacing on the majority of elements. This means go from 2rem to 1.5rem; 
- make headings slightly more spaced from generic divs like images etc, which was requested in https://github.com/canonical-web-and-design/vanilla-framework/issues/2420
- makes spacing under button match that under inputs and many other elements

## QA

- Pull code
- Run `./run serve --watch`
- Open examples/templates/typographic-spacing/ and scroll to the bottom
- Inspect the examples showing headings and paragraphs with different parents matching those in the same parents:
image
- Verify the image sits further from the heading:
image

- QA percy for visual changes

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
@deadlight need to fix the heading icon pattern, I'll remove the don't merge label once that's done

**Comment by lyubomir-popov** [comment]
As a quick visual summary, I'm going to attach a few screenshots here to explain what is changing:

- More spacing above a heading preceded by a generic classless element like a div or image:
image
- less spacing under a button, to bring it inline with spacing under an input select etc.:
image
image

- .5rem less padding on shallow strips so that padding matches the ubiquitous margin-bottom on elements, which is 1.5 rem ($spv-outer--scaleable):
image

- As a side benefit, the updated shallow strip depth allows us, at long last, to compensate for markup like this:
image

(Wrapping in a .p-strip-is-shallow.u-no-padding--bottom achieves the same spacing as p followed directly by an h2. The two columns show side by side regular vs wrapped headings being equally spaced).

**Comment by lyubomir-popov** [comment]
@kwm14 @deadlight ready for another look

**Comment by lyubomir-popov** [comment]
@kwm14 percy ready to review

**Comment by kwm14** [comment]
Nice work @lyubomir-popov spacing adjustments looking good across components. Only spotted one thing that needs updating is possible:

**/examples/patterns/matrix/index.html**
- [ ] At 375px viewport the text drops almost to the baseline of the icon compared to the current one, guessing this is due to the icon size change?

Screenshot 2019-08-21 at 16 51 09

**Comment by deadlight** [comment]
@lyubomir-popov the code looks much simpler

**Comment by lyubomir-popov** [comment]
@deadlight that's intended :)

**Comment by kwm14** [comment]
Design LGTM 👍

**Pull request merged**
