### PR TITLE
Improvements to borders and box shadows

### LINKED ISSUE #3492: Improve card box-shadow appearance
Currently cards in Vanilla have one single shadow appearance, one example of vanilla cards used is in the Charmhub directory. This is how it currently looks like: 

This box-shadow styling could feel unnatural, as shadows are more nuanced in reality. A good example covering this topic is following: 
https://tobiasahlin.com/blog/layered-smooth-box-shadows/

Currently, the box shadow values are expressed in one layer in the CSS, Using 2 ore more layers we could provide a more natural looking shadow effect for cards. One problem with the current shadows is that they are rendered as if light hits the cards right from the front, while most websites design shadows with a slightly higher light source (so shadow bounces off to the bottom of the card, making it taller than at the top of the card, similar to Material Design: https://material.io/design/environment/light-shadows.html#light)

While I am not saying that Material Design is right about everything, I'd say they got it right when it comes to key and ambient lights. Using this philosophy it would make sense we design box-shadow with 2 layers, one using a key light and one using an ambient light.

I have prototyped 3 different proposals in Sketch on how that could look like:

Option 1:

Option 2:

Option 3:

What do you think?

### PR DESCRIPTION
**Pull request by bartaz**
## Done

- Updates border color and box shadow values

Fixes #3492

## QA

- Open [demo](https://vanilla-framework-3648.demos.haus/docs)
- https://vanilla-framework-3648.demos.haus/docs/examples/patterns/card/highlighted
- https://vanilla-framework-3648.demos.haus/docs/examples/patterns/navigation/subnav
- https://vanilla-framework-3648.demos.haus/docs/examples/patterns/contextual-menu/default
- https://vanilla-framework-3648.demos.haus/docs/examples/patterns/modal/default
- https://vanilla-framework-3648.demos.haus/docs/examples/patterns/notifications/notifications
- https://vanilla-framework-3648.demos.haus/docs/examples/patterns/switch
- Review updated documentation:
  - [List any updated documentation for review]

### Check if PR is ready for release

If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure it's ready for the release:

- [x] PR should have one of the following labels to automatically categorise it in release notes:
  - `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, `Documentation 📝`, `Maintenance 🔨`.
- [x] Vanilla version in `package.json` should be updated relative to the [most recent release](https://github.com/canonical-web-and-design/vanilla-framework/releases/latest), following semver convention:
  - if CSS class names are not changed it can be bugfix relesase (x.x.**X**)
  - if CSS class names are changed/added/removed it should be minor version (x.**X**.0)
  - see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Release-process#pre-release-tasks)
- [x] Any changes to component class names (new patterns, variants, removed or added features) should be listed on the [component status page](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/templates/docs/component-status.md).
- [x] Documentation side navigation should be updated with the relevant labels.

## Screenshots

[if relevant, include a screenshot or screen capture]

### CODE REVIEW

**Comment by bartaz** [comment]
@lyubomir-popov I'm unsure what to do with this docs page (https://vanilla-framework-3648.demos.haus/docs/settings/placeholder-settings), now with triple box shadow value it's really hard to read.

Screenshot 2021-03-24 at 09 07 36

The other thing is that it doesn't seem it has been maintained at all, the values of bar-thickness and border-radius in pixels seem not to have been updated for  a while.

**Comment by anthonydillon** [comment]
We could document the variables and there usage with a link to the file in GitHub?

**Comment by bartaz** [comment]
> We could document the variables and there usage with a link to the file in GitHub? That might also go out of date though.

Yes, that's what I was thinking as well.

**Comment by lyubomir-popov** [comment]
@bartaz hmm fixing his page will take more than a drive-by I think. Clearly the content doesn't fit in a table, so we'd need to switch to a list of some sort. 

But the bigger issue I see here is that it list a tiny fraction of the existing placeholders, I don't think it's worth having the page unless it shows a much bigger portion of what is in that file.

**Comment by anthonydillon** [comment]
Remember the more we provide as options. The more complicated and bewildering it is for devs to use in our team. Which is our main goal. Provide solid and easy to use patterns that update without a hitch.

**Review by sowasred2012 — APPROVED** [review]
LGTM

**Comment by bartaz** [comment]
I ended up updateing the values, truncating, and also linking to the source file:

https://vanilla-framework-3648.demos.haus/docs/settings/placeholder-settings
Screenshot 2021-03-24 at 12 56 19

**Pull request merged**
