### PR TITLE
Clarify the usage of the dark-themed icons.

### PR DESCRIPTION
**Pull request by hatched**
## Done

Update the documentation around using the dark-themed icons.

Related #3366

### CODE REVIEW

**Review by anthonydillon — COMMENTED** [review]
What was the reason we wildcarded the `--dark` parent selector? I thought `p-strip--dark` and `is-dark` are the only parent selectors that should auto trigger the light icons?

**Review by lyubomir-popov — APPROVED** [review]
LGTM. Technically the selector will be matched regardless of whether `--dark` is a suffix. Wonder if we should explain that precisely - to reassure people that if they have to chain modifiers for whatever reason (e.g. `--dark-small`) it would still work.

**Comment by bartaz** [comment]
> What was the reason we wildcarded the `--dark` parent selector? I thought `p-strip--dark` and `is-dark` are the only parent selectors that should auto trigger the light icons?

I looked at history, and I don't know. It's 3 years old and basically first time we started having 'dark' version of icons it was using `--dark` already instead of `.p-strip--dark`. Having a quick search strips are the only ones that use `--dark` naming convention (because it predates our themed `is-dark` versions of other components).

While we technically use `--dark` I'm not sure if we should document and encourage usage of it. It's an exception that should not be used elsewhere and promoted. I would even say that it's arguable if the icons should even take external class names into account. While it makes things 'simpler' if icons are thrown directly into darks strips, it can easily lead to issues when dark parent container will be further up the document tree and actually a light version of icon will be expected.
In a long term (3.0, later?) I think we should remove icons being styled by strips and allow icon classnames to affect icon look.

**Comment by anthonydillon** [comment]
I agree, it would be good to remove this complexity and simply provide `p-icon--anchor is-inverted` which with switch to dark if using the light theme and vise versa.

**Comment by bartaz** [comment]
> I agree, it would be good to remove this complexity and simply provide `p-icon--anchor is-inverted` which with switch to dark if using the light theme and vise versa.

`is-inverted` would still make icons depend on theme of external component. For clarity and simplicity components should define their own theme, including icons.
But, that's not something we can change now without breaking changes, so we can think about it and decide closer to 3.0 release.

**Pull request merged**
