### PR TITLE
DEMO: New canonical.com primary/global nav prototype

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
- [Canonical nav demo](https://vanilla-framework-canonical-web-and-design-pr-2367.run.demo.haus/examples/templates/canonical-nav/) 
- [Interaction with ubuntu nav demo](https://vanilla-framework-canonical-web-and-design-pr-2367.run.demo.haus/examples/templates/canonical-ubuntu-navs/)
- [Animated suru demo](https://vanilla-framework-canonical-web-and-design-pr-2367.run.demo.haus/examples/templates/animated-suru/)
- [Sketch file](https://drive.google.com/open?id=1zl7TkOA_S7ibwDQSpnxrnSVVDCDYch3K)

This is a WIP PR to keep a demo running and to get a "feel" for how the new canonical.com nav might work.
**Note: this is not production code**. Once the look and feel has been finalised it will be rebuilt in a not so crappy way.

- [x] Build large variant (which would be the default on canonical.com)
- [x] Build small variant (as seen when on other sites)
- [x] Add animation to dropdowns
- [x] Build demo of interaction with ubuntu.com nav
- [ ] Build mobile version

## Design review iteration 1

- [x] Get rid of orange underline on primary nav
- [x] Remove strong font on selected secondary
- [x] Use tab spacing for secondary
- [x] Redo canonical ubuntu interaction with only secondary sticky
- [x] When canonical nav is small make text greyer
- [x] Remove suru
- [x] Increase gap on products dropdown between first matrix and "Also from Canonical"
- [x] Decrease opacity on ubuntu nav chevron
- [x] Bring careers headers down a level to h4 (https://usercontent.irccloud-cdn.com/file/gsQD5JNU/image.png)

## Design review iteration 2

- [x] Careers dropdown: make all links 16px and blue, not strong
- [x] Secondary nav: try active/hover state change font colour to orange
- [x] Secondary nav: try 2 rows of constrained bottom border
- [x] Ubuntu interaction: Increase secondary nav font-size to 16px
- [x] Ubuntu interaction: Only have in-page navigation sticky

### CODE REVIEW

**Comment by spencerbygraves** [comment]
@Caleb-Ellis do you want a design review on this yet?

**Comment by Caleb-Ellis** [comment]
@spencerbygraves Sure thing if you've got the time! There's still a bunch of stuff missing (icons, animations, mobile) so I'd just keep it general for now. My main issue is what to do about the long list of secondary links wrapping to a new line.

**Comment by Caleb-Ellis** [comment]
## Design review

- Get rid of orange underline on primary nav
- Remove strong font on selected secondary
- Use tab spacing for secondary
- Redo canonical ubuntu interaction with only openstack sticky
- When canonical nav is small make text greyer
- Remove suru for the demo
- Bring careers headers down a level to h4
- https://usercontent.irccloud-cdn.com/file/gsQD5JNU/image.png

**Comment by tbille** [comment]
Good old time

**Comment by Caleb-Ellis** [comment]
## Design review from iteration 2

- [ ] Careers dropdown: make all links 16px and blue, not strong
- [ ] Secondary nav: try active/hover state change font colour to orange
- [ ] Secondary nav: try 2 rows of constrained bottom border
- [ ] Ubuntu interaction: Increase secondary nav font-size to 16px
- [ ] Ubuntu interaction: Only have in-page navigation sticky

**Comment by kwm14** [comment]
@Caleb-Ellis @anthonydillon @pmahnke this PR still valid as I know work has started on the new Canonical site?

**Comment by Lukewh** [comment]
> @Caleb-Ellis @anthonydillon @pmahnke this PR still valid as I know work has started on the new Canonical site?

@kwm14 asking the important questions.

**Pull request closed without merging**
