### PR TITLE
Truncates modal to fit content and centers

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Truncates modal to fit where the content ends and centers the modal when viewing on mobile.

Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3906

## QA

- Open [demo](https://vanilla-framework-3982.demos.haus/docs/examples/patterns/modal/default)
- Check the modal works as expected and that it limits the size to fit that of the content.

### Check if PR is ready for release

If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure it's ready for the release:

- [x] PR should have one of the following labels to automatically categorise it in release notes:
  - `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, `Documentation 📝`, `Maintenance 🔨`.
- [x] Vanilla version in `package.json` should be updated relative to the [most recent release](https://github.com/canonical-web-and-design/vanilla-framework/releases/latest), following semver convention:
  - if CSS class names are not changed it can be bugfix relesase (x.x.**X**)
  - if CSS class names are changed/added/removed it should be minor version (x.**X**.0)
  - see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Release-process#pre-release-tasks)
- [x] Any changes to component class names (new patterns, variants, removed or added features) should be listed on the [what's new page](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/templates/docs/whats-new.md).
- [x] Documentation side navigation should be updated with the relevant labels.

## Screenshots

Screenshot from 2021-09-14 12-18-11

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
@bartaz one concern with the centering - what happens when, as a result of interaction, the height changes? this would jump to a different position.Should we have a version of this that is positionable in a fixed way, so that it doesn't move if you tick a checkbox and it reveals a couple more fields.

**Comment by bartaz** [comment]
> @bartaz one concern with the centering - what happens when, as a result of interaction, the height changes? this would jump to a different position.Should we have a version of this that is positionable in a fixed way, so that it doesn't move if you tick a checkbox and it reveals a couple more fields.

@lyubomir-popov We can fix it ourselves to the top (as it was before) without making it full screen. But it's also as easy as setting `top` in CSS or JS. So we can describe it in the docs.
But in such case we should have a recommendation - when dialogs should be aligned to the top and when not? Maybe for simplicity always align them from top?

**Comment by lyubomir-popov** [comment]
I'd say pick an optimum max height for the panel, and center that - then expand until you reach it, as needed.

**Review by bartaz — APPROVED** [review]
Looks good! Thanks

**Pull request merged**
