### PR TITLE
Fix pagination margins

### LINKED ISSUE #2459: Pagination cannot be centred exactly
**Describe the bug**
Using `u-align--center` on `p-pagination` centres pagination on the page but not exactly in the middle.

**To Reproduce**
1. Add `u-align--center` to pagination (ideally with some other centred element above it)
2. Check if pagination is exactly centred

**Expected behavior**
Pagination should center exactly in the middle of the page

**Screenshots**
Screenshot 2019-08-07 at 14 52 51

It happens possibly because of margin after last button:
Screenshot 2019-08-07 at 14 54 35

### PR DESCRIPTION
**Pull request by lyubomir-popov**
## Done

Fixes  #2459

## QA

- Pull code
- Run `./run serve --watch`
- /examples/patterns/pagination/pagination/
- add u-align--center to the pattern
- observe lack of margins on first/last element, which fixes the alignment issue mentioned in #2459

## Details

[List of links to issues/bugs and cards if needed]

## Screenshots

[if relevant, include a screenshot]

### CODE REVIEW

**Comment by kwm14** [comment]
## Design review
Truncated bullets no longer centered and moved to the left on https://vanilla-framework-canonical-web-and-design-pr-2511.run.demo.haus/examples/patterns/pagination/pagination-truncated/ based on your change.

**Desktop**
Screenshot 2019-08-27 at 10 28 17

**Mobile**
Screenshot 2019-08-27 at 10 28 25

**Comment by lyubomir-popov** [comment]
Updated to fix truncation and a few other things I noticed: 
- padding and height wasn't matching other inputs and buttons
- old chevron

To test, replace the contents of the truncation example with:
```
<div class="row">
  <div class="col-6">
<ol class="p-pagination">
  <li class="p-pagination__item">
    <a class="p-pagination__link--previous" href="#previous" title="Previous page"><i class="p-icon--contextual-menu">Previous page</i></a>
  </li>
  <li class="p-pagination__item">
    <a class="p-pagination__link" href="#1">1</a>
  </li>
  <li class="p-pagination__item p-pagination__item--truncation">
    …
  </li>
  <li class="p-pagination__item">
    <a class="p-pagination__link" href="#33">33</a>
  </li>
  <li class="p-pagination__item">
    <a class="p-pagination__link is-active" href="#34">34</a>
  </li>
  <li class="p-pagination__item">
    <a class="p-pagination__link" href="#35">35</a>
  </li>
  <li class="p-pagination__item p-pagination__item--truncation">
    …
  </li>
  <li class="p-pagination__item">
    <a class="p-pagination__link" href="#7">100</a>
  </li>
  <li class="p-pagination__item">
    <a class="p-pagination__link--next" href="#next" title="Next page"><i class="p-icon--contextual-menu">Next page</i></a>
  </li>
</ol>
  </div>
  <div class="col-2">
    <button>Button</button>
  </div>
  <div class="col-4">
    <input type="text">
  </div>
</div>```

**Comment by lyubomir-popov** [comment]
@kwm14 is there a reason why the numbers are buttons? Usually these are represented as just text links. Seems bulkier than it needs to be.

**Comment by kwm14** [comment]
Design updates LGTM 👍

**Comment by kwm14** [comment]
> @kwm14 is there a reason why the numbers are buttons? Usually these are represented as just text links. Seems bulkier than it needs to be.

@lyubomir-popov I explored a [few variations](https://github.com/canonical-web-and-design/design-vanilla-framework/issues/169) without it being inside a button, but this style got sign-oof from UX and Design. Happy to revisit in the future if any issues are raised.

**Pull request merged**
