### PR TITLE
develop changes to master

### PR DESCRIPTION
**Pull request by deadlight**
This is a merge of all changes in develop to the master branch ahead of the removal of the develop branch.

All of these changes have been individually reviewed on merge with develop so this PR is a test of the merge.

I have cleaned up some of the commit messages in an attempt to keep the branch history meaningful.

### CODE REVIEW

**Comment by deadlight** [comment]
@nottrobin following up the IRC message: Can you check this branch's infrastructure setup and let me know if there's anything that needs updating?

**Comment by deadlight** [comment]
Fixes #2275

**Comment by nottrobin** [comment]
@deadlight did you do the step of publishing the current master to `gh-pages`, and changing the GitHub setting to build from that branch? That needs to happen before this can be merged.

**Comment by kwm14** [comment]
Percy Diffs LGTM 👍

**Pull request merged**
