### PR TITLE
Apply !important on all properties of the .u-vertically-center utuility class

### LINKED ISSUE #3537: Align utility does not have !important on all properties it sets
image

### PR DESCRIPTION
**Pull request by lyubomir-popov**
## Done

Fixes #3537

## QA

- Inspect percy, ensure nothing looks wrong

### CODE REVIEW

**Review by bartaz — APPROVED** [review]
LGTM

**Review by bartaz — CHANGES_REQUESTED** [review]
Looking at percy it seems to be breaking some things.

Maybe these are some weird edge cases, but we should either update our examples to make them work as expected with this fix, or we should do it a bit differently.

**Comment by lyubomir-popov** [comment]
@bartaz ready for another look. The percy diff is down to this:

image

Seems like a 1px aliasing thing

**Review by bartaz — APPROVED** [review]
LGTM, thanks for updates!

**Pull request merged**
