### PR TITLE
Apply shallow strip padding to large lists

### LINKED ISSUE #1917: Add padding to stepped list detailed
## Pattern to amend
Stepped-list--detailed

## Context
The sections/descriptions part of the step has no padding between the one above. This makes it difficult to work out when one step stops and the next starts. This has been polyfilled on www.ubuntu.com with the following code:
```css
.p-stepped-list--detailed .p-list-step__item {
  margin-top: 1rem;
}
```

### PR DESCRIPTION
**Pull request by lyubomir-popov**
## Done

Fixes  #1917

## QA

- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo]
- Verify lists have padding top and bottom matching shallow strip

image

### CODE REVIEW

**Comment by anthonydillon** [comment]
@lyubomir-popov this branch adds extra padding top and bottom of lists which results in incorrect padding between strips. The strips provide a consistent padding thought the page and by adding additional we will have double padding on divider list strips for example.

It also does not resolve the issue. The issue is that each list item does not have enough padding.

**Comment by bartaz** [comment]
Seems like this branch was made on top of other branches (chips WIP, hover colors) rather than master.

**Comment by lyubomir-popov** [comment]
@anthonydillon hmm I was under the impression you wanted the stepped lists to have some top padding:

image

There's a huge amount of space between individual list items: 
image

**Comment by anthonydillon** [comment]
The space at the top is the reason I added margin top to each list item but the main issue is that when the details don't have enough space to distinguish which titles starts separates a detail block. As the image on the issue.

**Comment by lyubomir-popov** [comment]
@anthonydillon I added linked to the original wg issue that leads to a zeplin design proposal. Closing this.

**Pull request closed without merging**
